/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    DialogEdit: typeof import('./src/components/DialogEdit.vue')['default']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IntentBadge: typeof import('./src/components/IntentBadge.vue')['default']
    PopupMenu: typeof import('./src/components/PopupMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./src/components/SearchDialog.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    ToolCallCard: typeof import('./src/components/ToolCallCard.vue')['default']
  }
}
